### ISSUE TITLE
My Account Not Working on playshiftos.ml

### ISSUE THREAD

**Issue by carverh** [MichaelTheShifter/ShiftOS-C-#10]

**Comment by MichaelTheShifter** [comment]
I need some more information to be able to help out, the ACP logging system is unfinished so I can't really look at it to see user-related things.

**Comment by carverh** [comment]
Can't Post, Edit Account or Comment

**Comment by ComputeLinux** [comment]
Same error. It is super broken

**Comment by MichaelTheShifter** [comment]
Yeah, it's my first ASP.NET project, there's lots of kinks. Certainly needs some work.

**Comment by MichaelTheShifter** [comment]
Investigated the issue and it was a markdown parser bug that had to do with icon parsing (which turns {star} into a star for example).

It happens on any page which shows a user's signature (viewtopic, user control panel, etc) and it was trying to parse icons from a null string causing an NRE.

I don't really need icons so I removed 'em from markdown. If you still experience issues after my changes commit to the site, let me know and I'll look further :P

**Comment by ComputeLinux** [comment]
The problem was fixed.
