### ISSUE TITLE
releases.shiftos.ml's Dependencies zip is corrupted.

### ISSUE THREAD

**Issue by ComputeLinux** [MichaelTheShifter/ShiftOS-C-#11]
See title

**Comment by MichaelTheShifter** [comment]
That was alarming, I checked it through SSH, and I was able to extract everything just fine. Could you please provide more info? For example, is it extracting but there's missing files, or is Windows showing an error when opening the zip?

**Comment by ComputeLinux** [comment]
Yes, it extracts but gives unknown errors on certain files.

**Comment by MichaelTheShifter** [comment]
Weird. I'll have to update it once I finish `shiftui-integration`. For now please use the appveyor build or just compile from code :P

**Comment by carverh** [comment]
You have to Download the source code. There hasn't been a stable release yet so there is no ready release.
