### ISSUE TITLE
ShiftUI issues for me to note.

### ISSUE THREAD

**Issue by MichaelTheShifter** [MichaelTheShifter/ShiftOS-C-#18]
- [x] Auto scroll issue with terminal.
- [x] Flickery app launcher.
- [ ] Incomplete shifter (fixing in stream)
- [x] Every second appveyor build is failing.

**Comment by ComputeLinux** [comment]
Fixed half of these issues. Every appveyor build builds and the flickery applauncher isnt a real bug.
