### ISSUE TITLE
Cheat / Debug Mode

### ISSUE THREAD

**Issue by GabrielTK** [MichaelTheShifter/ShiftOS-C-#6]
Good Evening,
Have you ever thought about adding a Cheat / Debug mode, activated by an Easter egg, or maybe a variable change (Developers Only or Public)?? 
Can I start a PR???

**Comment by MichaelTheShifter** [comment]
There already is a cheat mode in unstable and AppVeyor builds - try the `05tray` and `linux` Terminal commands on any of these builds, see what you get. There is currently no way of cheating past the storyline, however.

**Comment by GabrielTK** [comment]
Ok, I was starting to develop a GUI for cheats. Are the commands registered at terminal.cs (In Apps)??
Also, if you don't mind, I'm without my computer, so, if you can, could you please tell me what this commands do??
Thank you very much,
Gabriel.

**Comment by MichaelTheShifter** [comment]
The commands are registered within Terminal.cs, yes, however it's best to use a LuaInterpreter object instead to interact with the system like that - for example you can do this:

```
var l = new LuaInterpreter(); //Instantiate a new instance of the ShiftOS Lua API
l.mod("terminal(\"05tray\")"); //Open a terminal, run the command "05tray".
l.mod("terminal(\"close terminal\")"); //Close the terminal you just opened.
```

Put that in a button click, and start spamming the button, and you'll get lots of Codepoints. Do the same for `linux`, and you'll end up with all the Shiftorium Upgrades you can get at the current point in the story. This is how I create my developer saves, actually.

**Comment by GabrielTK** [comment]
Are you using WinForms??? My VS2015 (with Resharper) is showing lots of errors

**Comment by MichaelTheShifter** [comment]
What is the designer that's throwing that error? In the future I'm moving to [ShiftUI](http://github.com/MichaelTheShifter/Project-Circle) which does _not_ have working VS designer support but it has it's own designer, but ShiftOS currently still uses plain old vanilla winforms.

**Comment by MichaelTheShifter** [comment]
Your PR has been merged to ShiftOS-C-/master. Closing!
